//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Brandranking 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("brandranking")]
	[Serializable]
	public partial class Brandranking : Entity 
	{
		#region Model
		private int _Id;
		private int? _IndustryID;
		private int? _BrandID;
		private string _BrandName;
		private string _CompanyName;
		private DateTime? _UpdateTime;
		private int? _Year;
		private int? _Rank;
		private int? _Status;
		private string _LOGO1;
		private string _LOGO2;
		private string _MailAddr;
		private string _Addr;
		private string _Websit;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 行业ID
		/// </summary>
		public int? IndustryID
		{
			get{ return _IndustryID; }
			set
			{
				this.OnPropertyValueChange(_.IndustryID,_IndustryID,value);
				this._IndustryID=value;
			}
		}
		/// <summary>
		/// 品牌ID
		/// </summary>
		public int? BrandID
		{
			get{ return _BrandID; }
			set
			{
				this.OnPropertyValueChange(_.BrandID,_BrandID,value);
				this._BrandID=value;
			}
		}
		/// <summary>
		/// 品牌名称
		/// </summary>
		public string BrandName
		{
			get{ return _BrandName; }
			set
			{
				this.OnPropertyValueChange(_.BrandName,_BrandName,value);
				this._BrandName=value;
			}
		}
		/// <summary>
		/// 品牌名称
		/// </summary>
		public string CompanyName
		{
			get{ return _CompanyName; }
			set
			{
				this.OnPropertyValueChange(_.CompanyName,_CompanyName,value);
				this._CompanyName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 年份
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 排名
		/// </summary>
		public int? Rank
		{
			get{ return _Rank; }
			set
			{
				this.OnPropertyValueChange(_.Rank,_Rank,value);
				this._Rank=value;
			}
		}
		/// <summary>
		/// 奖牌证书
		/// </summary>
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 证书
		/// </summary>
		public string LOGO1
		{
			get{ return _LOGO1; }
			set
			{
				this.OnPropertyValueChange(_.LOGO1,_LOGO1,value);
				this._LOGO1=value;
			}
		}
		/// <summary>
		/// 奖牌
		/// </summary>
		public string LOGO2
		{
			get{ return _LOGO2; }
			set
			{
				this.OnPropertyValueChange(_.LOGO2,_LOGO2,value);
				this._LOGO2=value;
			}
		}
		/// <summary>
		/// 邮寄地址
		/// </summary>
		public string MailAddr
		{
			get{ return _MailAddr; }
			set
			{
				this.OnPropertyValueChange(_.MailAddr,_MailAddr,value);
				this._MailAddr=value;
			}
		}
		/// <summary>
		/// 公司地址
		/// </summary>
		public string Addr
		{
			get{ return _Addr; }
			set
			{
				this.OnPropertyValueChange(_.Addr,_Addr,value);
				this._Addr=value;
			}
		}
		/// <summary>
		/// 官网
		/// </summary>
		public string Websit
		{
			get{ return _Websit; }
			set
			{
				this.OnPropertyValueChange(_.Websit,_Websit,value);
				this._Websit=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.IndustryID,
				_.BrandID,
				_.BrandName,
				_.CompanyName,
				_.UpdateTime,
				_.Year,
				_.Rank,
				_.Status,
				_.LOGO1,
				_.LOGO2,
				_.MailAddr,
				_.Addr,
				_.Websit};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._IndustryID,
				this._BrandID,
				this._BrandName,
				this._CompanyName,
				this._UpdateTime,
				this._Year,
				this._Rank,
				this._Status,
				this._LOGO1,
				this._LOGO2,
				this._MailAddr,
				this._Addr,
				this._Websit};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","brandranking");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","brandranking","编号");
			/// <summary>
			/// 行业ID
			/// </summary>
			public readonly static Field IndustryID = new Field("IndustryID","brandranking","行业ID");
			/// <summary>
			/// 品牌ID
			/// </summary>
			public readonly static Field BrandID = new Field("BrandID","brandranking","品牌ID");
			/// <summary>
			/// 品牌名称
			/// </summary>
			public readonly static Field BrandName = new Field("BrandName","brandranking","品牌名称");
			/// <summary>
			/// 品牌名称
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName","brandranking","品牌名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","brandranking","UpdateTime");
			/// <summary>
			/// 年份
			/// </summary>
			public readonly static Field Year = new Field("Year","brandranking","年份");
			/// <summary>
			/// 排名
			/// </summary>
			public readonly static Field Rank = new Field("Rank","brandranking","排名");
			/// <summary>
			/// 奖牌证书
			/// </summary>
			public readonly static Field Status = new Field("Status","brandranking","奖牌证书");
			/// <summary>
			/// 证书
			/// </summary>
			public readonly static Field LOGO1 = new Field("LOGO1","brandranking","证书");
			/// <summary>
			/// 奖牌
			/// </summary>
			public readonly static Field LOGO2 = new Field("LOGO2","brandranking","奖牌");
			/// <summary>
			/// 邮寄地址
			/// </summary>
			public readonly static Field MailAddr = new Field("MailAddr","brandranking","邮寄地址");
			/// <summary>
			/// 公司地址
			/// </summary>
			public readonly static Field Addr = new Field("Addr","brandranking","公司地址");
			/// <summary>
			/// 官网
			/// </summary>
			public readonly static Field Websit = new Field("Websit","brandranking","官网");
		}
		#endregion


	}
}

