//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Comment 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("comment")]
	[Serializable]
	public partial class Comment : Entity 
	{
		#region Model
		private int _Id;
		private int? _CreatorId;
		private string _IP;
		private string _From;
		private bool? _Ano;
		private string _Name;
		private string _Tel;
		private string _Email;
		private string _QQ;
		private string _Ali;
		private string _MSN;
		private string _Skype;
		private string _Text;
		private DateTime? _CreateDate;
		private string _Reply;
		private int? _ReplyUser;
		private bool? _Shown;
		private DateTime? _UpdateDate;
		private int? _RejectCount;
		private int? _RefCount;
		private int? _SupportCount;
		private int? _BrandID;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 创建人编号 如果Id为0表示guest
		/// </summary>
		public int? CreatorId
		{
			get{ return _CreatorId; }
			set
			{
				this.OnPropertyValueChange(_.CreatorId,_CreatorId,value);
				this._CreatorId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IP
		{
			get{ return _IP; }
			set
			{
				this.OnPropertyValueChange(_.IP,_IP,value);
				this._IP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string From
		{
			get{ return _From; }
			set
			{
				this.OnPropertyValueChange(_.From,_From,value);
				this._From=value;
			}
		}
		/// <summary>
		/// 是否匿名
		/// </summary>
		public bool? Ano
		{
			get{ return _Ano; }
			set
			{
				this.OnPropertyValueChange(_.Ano,_Ano,value);
				this._Ano=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange(_.Tel,_Tel,value);
				this._Tel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 阿里旺旺
		/// </summary>
		public string Ali
		{
			get{ return _Ali; }
			set
			{
				this.OnPropertyValueChange(_.Ali,_Ali,value);
				this._Ali=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MSN
		{
			get{ return _MSN; }
			set
			{
				this.OnPropertyValueChange(_.MSN,_MSN,value);
				this._MSN=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Skype
		{
			get{ return _Skype; }
			set
			{
				this.OnPropertyValueChange(_.Skype,_Skype,value);
				this._Skype=value;
			}
		}
		/// <summary>
		/// 内容
		/// </summary>
		public string Text
		{
			get{ return _Text; }
			set
			{
				this.OnPropertyValueChange(_.Text,_Text,value);
				this._Text=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Reply
		{
			get{ return _Reply; }
			set
			{
				this.OnPropertyValueChange(_.Reply,_Reply,value);
				this._Reply=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ReplyUser
		{
			get{ return _ReplyUser; }
			set
			{
				this.OnPropertyValueChange(_.ReplyUser,_ReplyUser,value);
				this._ReplyUser=value;
			}
		}
		/// <summary>
		/// 是否显示
		/// </summary>
		public bool? Shown
		{
			get{ return _Shown; }
			set
			{
				this.OnPropertyValueChange(_.Shown,_Shown,value);
				this._Shown=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateDate
		{
			get{ return _UpdateDate; }
			set
			{
				this.OnPropertyValueChange(_.UpdateDate,_UpdateDate,value);
				this._UpdateDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? RejectCount
		{
			get{ return _RejectCount; }
			set
			{
				this.OnPropertyValueChange(_.RejectCount,_RejectCount,value);
				this._RejectCount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? RefCount
		{
			get{ return _RefCount; }
			set
			{
				this.OnPropertyValueChange(_.RefCount,_RefCount,value);
				this._RefCount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SupportCount
		{
			get{ return _SupportCount; }
			set
			{
				this.OnPropertyValueChange(_.SupportCount,_SupportCount,value);
				this._SupportCount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? BrandID
		{
			get{ return _BrandID; }
			set
			{
				this.OnPropertyValueChange(_.BrandID,_BrandID,value);
				this._BrandID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.CreatorId,
				_.IP,
				_.From,
				_.Ano,
				_.Name,
				_.Tel,
				_.Email,
				_.QQ,
				_.Ali,
				_.MSN,
				_.Skype,
				_.Text,
				_.CreateDate,
				_.Reply,
				_.ReplyUser,
				_.Shown,
				_.UpdateDate,
				_.RejectCount,
				_.RefCount,
				_.SupportCount,
				_.BrandID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._CreatorId,
				this._IP,
				this._From,
				this._Ano,
				this._Name,
				this._Tel,
				this._Email,
				this._QQ,
				this._Ali,
				this._MSN,
				this._Skype,
				this._Text,
				this._CreateDate,
				this._Reply,
				this._ReplyUser,
				this._Shown,
				this._UpdateDate,
				this._RejectCount,
				this._RefCount,
				this._SupportCount,
				this._BrandID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","comment");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","comment","编号");
			/// <summary>
			/// 创建人编号 如果Id为0表示guest
			/// </summary>
			public readonly static Field CreatorId = new Field("CreatorId","comment","创建人编号 如果Id为0表示guest");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IP = new Field("IP","comment","IP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field From = new Field("From","comment","From");
			/// <summary>
			/// 是否匿名
			/// </summary>
			public readonly static Field Ano = new Field("Ano","comment","是否匿名");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","comment","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tel = new Field("Tel","comment","Tel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","comment","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QQ = new Field("QQ","comment","QQ");
			/// <summary>
			/// 阿里旺旺
			/// </summary>
			public readonly static Field Ali = new Field("Ali","comment","阿里旺旺");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MSN = new Field("MSN","comment","MSN");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Skype = new Field("Skype","comment","Skype");
			/// <summary>
			/// 内容
			/// </summary>
			public readonly static Field Text = new Field("Text","comment","内容");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","comment","CreateDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Reply = new Field("Reply","comment","Reply");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyUser = new Field("ReplyUser","comment","ReplyUser");
			/// <summary>
			/// 是否显示
			/// </summary>
			public readonly static Field Shown = new Field("Shown","comment","是否显示");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateDate = new Field("UpdateDate","comment","UpdateDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RejectCount = new Field("RejectCount","comment","RejectCount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RefCount = new Field("RefCount","comment","RefCount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SupportCount = new Field("SupportCount","comment","SupportCount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BrandID = new Field("BrandID","comment","BrandID");
		}
		#endregion


	}
}

