//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Company 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("company")]
	[Serializable]
	public partial class Company : Entity 
	{
		#region Model
		private int _Id;
		private DateTime? _CreateDate;
		private string _Name;
		private string _CRegisterNumber;
		private string _Addr;
		private string _Area;
		private string _AuditImage1;
		private string _AuditImage2;
		private string _AuditImage3;
		private bool _Audit;
		private int? _MemberID;
		private int? _AuditUserID;
		private string _Tel;
		private string _Fax;
		private string _Email;
		private string _Websit;
		private int? _StartYear;
		private string _RejectReason;
		private int? _Type;
		private string _MainIndustry;
		private string _BusinessRange;
		private int? _Mode;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 公司名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 公司注册证号
		/// </summary>
		public string CRegisterNumber
		{
			get{ return _CRegisterNumber; }
			set
			{
				this.OnPropertyValueChange(_.CRegisterNumber,_CRegisterNumber,value);
				this._CRegisterNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Addr
		{
			get{ return _Addr; }
			set
			{
				this.OnPropertyValueChange(_.Addr,_Addr,value);
				this._Addr=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Area
		{
			get{ return _Area; }
			set
			{
				this.OnPropertyValueChange(_.Area,_Area,value);
				this._Area=value;
			}
		}
		/// <summary>
		/// 认证图片1
		/// </summary>
		public string AuditImage1
		{
			get{ return _AuditImage1; }
			set
			{
				this.OnPropertyValueChange(_.AuditImage1,_AuditImage1,value);
				this._AuditImage1=value;
			}
		}
		/// <summary>
		/// 认证图片2
		/// </summary>
		public string AuditImage2
		{
			get{ return _AuditImage2; }
			set
			{
				this.OnPropertyValueChange(_.AuditImage2,_AuditImage2,value);
				this._AuditImage2=value;
			}
		}
		/// <summary>
		/// 认证图片3
		/// </summary>
		public string AuditImage3
		{
			get{ return _AuditImage3; }
			set
			{
				this.OnPropertyValueChange(_.AuditImage3,_AuditImage3,value);
				this._AuditImage3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool Audit
		{
			get{ return _Audit; }
			set
			{
				this.OnPropertyValueChange(_.Audit,_Audit,value);
				this._Audit=value;
			}
		}
		/// <summary>
		/// 会员ID
		/// </summary>
		public int? MemberID
		{
			get{ return _MemberID; }
			set
			{
				this.OnPropertyValueChange(_.MemberID,_MemberID,value);
				this._MemberID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AuditUserID
		{
			get{ return _AuditUserID; }
			set
			{
				this.OnPropertyValueChange(_.AuditUserID,_AuditUserID,value);
				this._AuditUserID=value;
			}
		}
		/// <summary>
		/// 公司电话
		/// </summary>
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange(_.Tel,_Tel,value);
				this._Tel=value;
			}
		}
		/// <summary>
		/// 传真
		/// </summary>
		public string Fax
		{
			get{ return _Fax; }
			set
			{
				this.OnPropertyValueChange(_.Fax,_Fax,value);
				this._Fax=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 官方网站
		/// </summary>
		public string Websit
		{
			get{ return _Websit; }
			set
			{
				this.OnPropertyValueChange(_.Websit,_Websit,value);
				this._Websit=value;
			}
		}
		/// <summary>
		/// 成立年份
		/// </summary>
		public int? StartYear
		{
			get{ return _StartYear; }
			set
			{
				this.OnPropertyValueChange(_.StartYear,_StartYear,value);
				this._StartYear=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RejectReason
		{
			get{ return _RejectReason; }
			set
			{
				this.OnPropertyValueChange(_.RejectReason,_RejectReason,value);
				this._RejectReason=value;
			}
		}
		/// <summary>
		/// 公司类型 私营，国有，独资，
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 主营行业
		/// </summary>
		public string MainIndustry
		{
			get{ return _MainIndustry; }
			set
			{
				this.OnPropertyValueChange(_.MainIndustry,_MainIndustry,value);
				this._MainIndustry=value;
			}
		}
		/// <summary>
		/// 经营范围
		/// </summary>
		public string BusinessRange
		{
			get{ return _BusinessRange; }
			set
			{
				this.OnPropertyValueChange(_.BusinessRange,_BusinessRange,value);
				this._BusinessRange=value;
			}
		}
		/// <summary>
		/// 经营模式 制造商，贸易商，，，
		/// </summary>
		public int? Mode
		{
			get{ return _Mode; }
			set
			{
				this.OnPropertyValueChange(_.Mode,_Mode,value);
				this._Mode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.CreateDate,
				_.Name,
				_.CRegisterNumber,
				_.Addr,
				_.Area,
				_.AuditImage1,
				_.AuditImage2,
				_.AuditImage3,
				_.Audit,
				_.MemberID,
				_.AuditUserID,
				_.Tel,
				_.Fax,
				_.Email,
				_.Websit,
				_.StartYear,
				_.RejectReason,
				_.Type,
				_.MainIndustry,
				_.BusinessRange,
				_.Mode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._CreateDate,
				this._Name,
				this._CRegisterNumber,
				this._Addr,
				this._Area,
				this._AuditImage1,
				this._AuditImage2,
				this._AuditImage3,
				this._Audit,
				this._MemberID,
				this._AuditUserID,
				this._Tel,
				this._Fax,
				this._Email,
				this._Websit,
				this._StartYear,
				this._RejectReason,
				this._Type,
				this._MainIndustry,
				this._BusinessRange,
				this._Mode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","company");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","company","编号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","company","CreateDate");
			/// <summary>
			/// 公司名称
			/// </summary>
			public readonly static Field Name = new Field("Name","company","公司名称");
			/// <summary>
			/// 公司注册证号
			/// </summary>
			public readonly static Field CRegisterNumber = new Field("CRegisterNumber","company","公司注册证号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Addr = new Field("Addr","company","Addr");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Area = new Field("Area","company","Area");
			/// <summary>
			/// 认证图片1
			/// </summary>
			public readonly static Field AuditImage1 = new Field("AuditImage1","company","认证图片1");
			/// <summary>
			/// 认证图片2
			/// </summary>
			public readonly static Field AuditImage2 = new Field("AuditImage2","company","认证图片2");
			/// <summary>
			/// 认证图片3
			/// </summary>
			public readonly static Field AuditImage3 = new Field("AuditImage3","company","认证图片3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Audit = new Field("Audit","company","Audit");
			/// <summary>
			/// 会员ID
			/// </summary>
			public readonly static Field MemberID = new Field("MemberID","company","会员ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditUserID = new Field("AuditUserID","company","AuditUserID");
			/// <summary>
			/// 公司电话
			/// </summary>
			public readonly static Field Tel = new Field("Tel","company","公司电话");
			/// <summary>
			/// 传真
			/// </summary>
			public readonly static Field Fax = new Field("Fax","company","传真");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","company","Email");
			/// <summary>
			/// 官方网站
			/// </summary>
			public readonly static Field Websit = new Field("Websit","company","官方网站");
			/// <summary>
			/// 成立年份
			/// </summary>
			public readonly static Field StartYear = new Field("StartYear","company","成立年份");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RejectReason = new Field("RejectReason","company","RejectReason");
			/// <summary>
			/// 公司类型 私营，国有，独资，
			/// </summary>
			public readonly static Field Type = new Field("Type","company","公司类型 私营，国有，独资，");
			/// <summary>
			/// 主营行业
			/// </summary>
			public readonly static Field MainIndustry = new Field("MainIndustry","company","主营行业");
			/// <summary>
			/// 经营范围
			/// </summary>
			public readonly static Field BusinessRange = new Field("BusinessRange","company","经营范围");
			/// <summary>
			/// 经营模式 制造商，贸易商，，，
			/// </summary>
			public readonly static Field Mode = new Field("Mode","company","经营模式 制造商，贸易商，，，");
		}
		#endregion


	}
}

