//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Contract 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("contract")]
	[Serializable]
	public partial class Contract : Entity 
	{
		#region Model
		private int _Id;
		private int? _BrandID;
		private string _CompanyName;
		private string _View;
		private DateTime? _CreateDate;
		private string _ViewBill;
		private int? _Charge;
		private int? _UserID;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 品牌编号
		/// </summary>
		public int? BrandID
		{
			get{ return _BrandID; }
			set
			{
				this.OnPropertyValueChange(_.BrandID,_BrandID,value);
				this._BrandID=value;
			}
		}
		/// <summary>
		/// 公司名称
		/// </summary>
		public string CompanyName
		{
			get{ return _CompanyName; }
			set
			{
				this.OnPropertyValueChange(_.CompanyName,_CompanyName,value);
				this._CompanyName=value;
			}
		}
		/// <summary>
		/// 合同截图
		/// </summary>
		public string View
		{
			get{ return _View; }
			set
			{
				this.OnPropertyValueChange(_.View,_View,value);
				this._View=value;
			}
		}
		/// <summary>
		/// 创建日期
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 发票截图
		/// </summary>
		public string ViewBill
		{
			get{ return _ViewBill; }
			set
			{
				this.OnPropertyValueChange(_.ViewBill,_ViewBill,value);
				this._ViewBill=value;
			}
		}
		/// <summary>
		/// 费用
		/// </summary>
		public int? Charge
		{
			get{ return _Charge; }
			set
			{
				this.OnPropertyValueChange(_.Charge,_Charge,value);
				this._Charge=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.BrandID,
				_.CompanyName,
				_.View,
				_.CreateDate,
				_.ViewBill,
				_.Charge,
				_.UserID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._BrandID,
				this._CompanyName,
				this._View,
				this._CreateDate,
				this._ViewBill,
				this._Charge,
				this._UserID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","contract");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","contract","编号");
			/// <summary>
			/// 品牌编号
			/// </summary>
			public readonly static Field BrandID = new Field("BrandID","contract","品牌编号");
			/// <summary>
			/// 公司名称
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName","contract","公司名称");
			/// <summary>
			/// 合同截图
			/// </summary>
			public readonly static Field View = new Field("View","contract","合同截图");
			/// <summary>
			/// 创建日期
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","contract","创建日期");
			/// <summary>
			/// 发票截图
			/// </summary>
			public readonly static Field ViewBill = new Field("ViewBill","contract","发票截图");
			/// <summary>
			/// 费用
			/// </summary>
			public readonly static Field Charge = new Field("Charge","contract","费用");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID","contract","UserID");
		}
		#endregion


	}
}

