//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Industry 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("industry")]
	[Serializable]
	public partial class Industry : Entity 
	{
		#region Model
		private int _Id;
		private int? _UserID;
		private string _Name;
		private string _Note;
		private int? _CreatorId;
		private DateTime _CreateTime;
		private int _Status;
		private int _ParentID;
		private string _SEOTitle;
		private string _Meta_Keywords;
		private string _Meta_Desc;
		private int? _AuditLimit;
		private int? _VoteLimit;
		private int? _Level;
		private string _CharIndex;
		private string _EName;
		private bool _ClosePC;
		private DateTime? _BeginDate;
		private DateTime? _EndDate;
		private string _VoteDesc;
		private string _VoteDesc1;
		private string _PublishUrl;
		private string _QRCodeUrl;
		private string _AutoCommnet;
		private bool _IsDelete;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 关联编号
		/// </summary>
		public int? UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 注释
		/// </summary>
		public string Note
		{
			get{ return _Note; }
			set
			{
				this.OnPropertyValueChange(_.Note,_Note,value);
				this._Note=value;
			}
		}
		/// <summary>
		/// 创建人编号
		/// </summary>
		public int? CreatorId
		{
			get{ return _CreatorId; }
			set
			{
				this.OnPropertyValueChange(_.CreatorId,_CreatorId,value);
				this._CreatorId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 状态
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ParentID
		{
			get{ return _ParentID; }
			set
			{
				this.OnPropertyValueChange(_.ParentID,_ParentID,value);
				this._ParentID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SEOTitle
		{
			get{ return _SEOTitle; }
			set
			{
				this.OnPropertyValueChange(_.SEOTitle,_SEOTitle,value);
				this._SEOTitle=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Meta_Keywords
		{
			get{ return _Meta_Keywords; }
			set
			{
				this.OnPropertyValueChange(_.Meta_Keywords,_Meta_Keywords,value);
				this._Meta_Keywords=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Meta_Desc
		{
			get{ return _Meta_Desc; }
			set
			{
				this.OnPropertyValueChange(_.Meta_Desc,_Meta_Desc,value);
				this._Meta_Desc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AuditLimit
		{
			get{ return _AuditLimit; }
			set
			{
				this.OnPropertyValueChange(_.AuditLimit,_AuditLimit,value);
				this._AuditLimit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? VoteLimit
		{
			get{ return _VoteLimit; }
			set
			{
				this.OnPropertyValueChange(_.VoteLimit,_VoteLimit,value);
				this._VoteLimit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Level
		{
			get{ return _Level; }
			set
			{
				this.OnPropertyValueChange(_.Level,_Level,value);
				this._Level=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CharIndex
		{
			get{ return _CharIndex; }
			set
			{
				this.OnPropertyValueChange(_.CharIndex,_CharIndex,value);
				this._CharIndex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string EName
		{
			get{ return _EName; }
			set
			{
				this.OnPropertyValueChange(_.EName,_EName,value);
				this._EName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool ClosePC
		{
			get{ return _ClosePC; }
			set
			{
				this.OnPropertyValueChange(_.ClosePC,_ClosePC,value);
				this._ClosePC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? BeginDate
		{
			get{ return _BeginDate; }
			set
			{
				this.OnPropertyValueChange(_.BeginDate,_BeginDate,value);
				this._BeginDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndDate
		{
			get{ return _EndDate; }
			set
			{
				this.OnPropertyValueChange(_.EndDate,_EndDate,value);
				this._EndDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string VoteDesc
		{
			get{ return _VoteDesc; }
			set
			{
				this.OnPropertyValueChange(_.VoteDesc,_VoteDesc,value);
				this._VoteDesc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string VoteDesc1
		{
			get{ return _VoteDesc1; }
			set
			{
				this.OnPropertyValueChange(_.VoteDesc1,_VoteDesc1,value);
				this._VoteDesc1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PublishUrl
		{
			get{ return _PublishUrl; }
			set
			{
				this.OnPropertyValueChange(_.PublishUrl,_PublishUrl,value);
				this._PublishUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QRCodeUrl
		{
			get{ return _QRCodeUrl; }
			set
			{
				this.OnPropertyValueChange(_.QRCodeUrl,_QRCodeUrl,value);
				this._QRCodeUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AutoCommnet
		{
			get{ return _AutoCommnet; }
			set
			{
				this.OnPropertyValueChange(_.AutoCommnet,_AutoCommnet,value);
				this._AutoCommnet=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsDelete
		{
			get{ return _IsDelete; }
			set
			{
				this.OnPropertyValueChange(_.IsDelete,_IsDelete,value);
				this._IsDelete=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.UserID,
				_.Name,
				_.Note,
				_.CreatorId,
				_.CreateTime,
				_.Status,
				_.ParentID,
				_.SEOTitle,
				_.Meta_Keywords,
				_.Meta_Desc,
				_.AuditLimit,
				_.VoteLimit,
				_.Level,
				_.CharIndex,
				_.EName,
				_.ClosePC,
				_.BeginDate,
				_.EndDate,
				_.VoteDesc,
				_.VoteDesc1,
				_.PublishUrl,
				_.QRCodeUrl,
				_.AutoCommnet,
				_.IsDelete};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._UserID,
				this._Name,
				this._Note,
				this._CreatorId,
				this._CreateTime,
				this._Status,
				this._ParentID,
				this._SEOTitle,
				this._Meta_Keywords,
				this._Meta_Desc,
				this._AuditLimit,
				this._VoteLimit,
				this._Level,
				this._CharIndex,
				this._EName,
				this._ClosePC,
				this._BeginDate,
				this._EndDate,
				this._VoteDesc,
				this._VoteDesc1,
				this._PublishUrl,
				this._QRCodeUrl,
				this._AutoCommnet,
				this._IsDelete};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","industry");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","industry","编号");
			/// <summary>
			/// 关联编号
			/// </summary>
			public readonly static Field UserID = new Field("UserID","industry","关联编号");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","industry","名称");
			/// <summary>
			/// 注释
			/// </summary>
			public readonly static Field Note = new Field("Note","industry","注释");
			/// <summary>
			/// 创建人编号
			/// </summary>
			public readonly static Field CreatorId = new Field("CreatorId","industry","创建人编号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","industry","CreateTime");
			/// <summary>
			/// 状态
			/// </summary>
			public readonly static Field Status = new Field("Status","industry","状态");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentID = new Field("ParentID","industry","ParentID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SEOTitle = new Field("SEOTitle","industry","SEOTitle");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Meta_Keywords = new Field("Meta_Keywords","industry","Meta_Keywords");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Meta_Desc = new Field("Meta_Desc","industry","Meta_Desc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditLimit = new Field("AuditLimit","industry","AuditLimit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteLimit = new Field("VoteLimit","industry","VoteLimit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Level = new Field("Level","industry","Level");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CharIndex = new Field("CharIndex","industry","CharIndex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EName = new Field("EName","industry","EName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClosePC = new Field("ClosePC","industry","ClosePC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BeginDate = new Field("BeginDate","industry","BeginDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate","industry","EndDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteDesc = new Field("voteDesc","industry","voteDesc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteDesc1 = new Field("voteDesc1","industry","voteDesc1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PublishUrl = new Field("PublishUrl","industry","PublishUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QRCodeUrl = new Field("QRCodeUrl","industry","QRCodeUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoCommnet = new Field("AutoCommnet","industry","AutoCommnet");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDelete = new Field("IsDelete","industry","IsDelete");
		}
		#endregion


	}
}

