//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Ranking 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ranking")]
	[Serializable]
	public partial class Ranking : Entity 
	{
		#region Model
		private int _Id;
		private int? _IndustryID;
		private DateTime? _CreateDate;
		private int? _ViewCount;
		private string _Title;
		private int _Year;
		private string _RankingList;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 行业编号
		/// </summary>
		public int? IndustryID
		{
			get{ return _IndustryID; }
			set
			{
				this.OnPropertyValueChange(_.IndustryID,_IndustryID,value);
				this._IndustryID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 浏览数
		/// </summary>
		public int? ViewCount
		{
			get{ return _ViewCount; }
			set
			{
				this.OnPropertyValueChange(_.ViewCount,_ViewCount,value);
				this._ViewCount=value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 年份
		/// </summary>
		public int Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 榜单明细 备份用，brand id,
		/// </summary>
		public string RankingList
		{
			get{ return _RankingList; }
			set
			{
				this.OnPropertyValueChange(_.RankingList,_RankingList,value);
				this._RankingList=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.IndustryID,
				_.CreateDate,
				_.ViewCount,
				_.Title,
				_.Year,
				_.RankingList};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._IndustryID,
				this._CreateDate,
				this._ViewCount,
				this._Title,
				this._Year,
				this._RankingList};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ranking");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","ranking","编号");
			/// <summary>
			/// 行业编号
			/// </summary>
			public readonly static Field IndustryID = new Field("IndustryID","ranking","行业编号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","ranking","CreateDate");
			/// <summary>
			/// 浏览数
			/// </summary>
			public readonly static Field ViewCount = new Field("ViewCount","ranking","浏览数");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title","ranking","标题");
			/// <summary>
			/// 年份
			/// </summary>
			public readonly static Field Year = new Field("Year","ranking","年份");
			/// <summary>
			/// 榜单明细 备份用，brand id,
			/// </summary>
			public readonly static Field RankingList = new Field("RankingList","ranking","榜单明细 备份用，brand id,");
		}
		#endregion


	}
}

