//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Role 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("role")]
	[Serializable]
	public partial class Role : Entity 
	{
		#region Model
		private int _Id;
		private string _CName;
		private string _Value;
		private string _Note;
		private DateTime? _CreateTime;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 注释 中文名
		/// </summary>
		public string CName
		{
			get{ return _CName; }
			set
			{
				this.OnPropertyValueChange(_.CName,_CName,value);
				this._CName=value;
			}
		}
		/// <summary>
		/// 注释 用，分隔不同的权限
		/// </summary>
		public string Value
		{
			get{ return _Value; }
			set
			{
				this.OnPropertyValueChange(_.Value,_Value,value);
				this._Value=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get{ return _Note; }
			set
			{
				this.OnPropertyValueChange(_.Note,_Note,value);
				this._Note=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.CName,
				_.Value,
				_.Note,
				_.CreateTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._CName,
				this._Value,
				this._Note,
				this._CreateTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","role");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","role","编号");
			/// <summary>
			/// 注释 中文名
			/// </summary>
			public readonly static Field CName = new Field("CName","role","注释 中文名");
			/// <summary>
			/// 注释 用，分隔不同的权限
			/// </summary>
			public readonly static Field Value = new Field("Value","role","注释 用，分隔不同的权限");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Note = new Field("Note","role","Note");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","role","CreateTime");
		}
		#endregion


	}
}

