//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Ticketcache 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ticketcache")]
	[Serializable]
	public partial class Ticketcache : Entity 
	{
		#region Model
		private int _Id;
		private int? _BrandID;
		private string _IP;
		private string _Weibo;
		private string _Weixin;
		private string _Qq;
		private string _PhoneNumber;
		private string _PhoneInfo;
		private int? _PhoneHash;
		private DateTime? _CreateTime;
		private int? _Type;
		private string _Note;
		private string _Area;
		private int _NoteHash;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 关联编号
		/// </summary>
		public int? BrandID
		{
			get{ return _BrandID; }
			set
			{
				this.OnPropertyValueChange(_.BrandID,_BrandID,value);
				this._BrandID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IP
		{
			get{ return _IP; }
			set
			{
				this.OnPropertyValueChange(_.IP,_IP,value);
				this._IP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Weibo
		{
			get{ return _Weibo; }
			set
			{
				this.OnPropertyValueChange(_.Weibo,_Weibo,value);
				this._Weibo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Weixin
		{
			get{ return _Weixin; }
			set
			{
				this.OnPropertyValueChange(_.Weixin,_Weixin,value);
				this._Weixin=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Qq
		{
			get{ return _Qq; }
			set
			{
				this.OnPropertyValueChange(_.Qq,_Qq,value);
				this._Qq=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PhoneNumber
		{
			get{ return _PhoneNumber; }
			set
			{
				this.OnPropertyValueChange(_.PhoneNumber,_PhoneNumber,value);
				this._PhoneNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PhoneInfo
		{
			get{ return _PhoneInfo; }
			set
			{
				this.OnPropertyValueChange(_.PhoneInfo,_PhoneInfo,value);
				this._PhoneInfo=value;
			}
		}
		/// <summary>
		/// 由phoneInfo getHash
		/// </summary>
		public int? PhoneHash
		{
			get{ return _PhoneHash; }
			set
			{
				this.OnPropertyValueChange(_.PhoneHash,_PhoneHash,value);
				this._PhoneHash=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// TRUE,AUTO,
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 注释
		/// </summary>
		public string Note
		{
			get{ return _Note; }
			set
			{
				this.OnPropertyValueChange(_.Note,_Note,value);
				this._Note=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Area
		{
			get{ return _Area; }
			set
			{
				this.OnPropertyValueChange(_.Area,_Area,value);
				this._Area=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int NoteHash
		{
			get{ return _NoteHash; }
			set
			{
				this.OnPropertyValueChange(_.NoteHash,_NoteHash,value);
				this._NoteHash=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.BrandID,
				_.IP,
				_.Weibo,
				_.Weixin,
				_.Qq,
				_.PhoneNumber,
				_.PhoneInfo,
				_.PhoneHash,
				_.CreateTime,
				_.Type,
				_.Note,
				_.Area,
				_.NoteHash};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._BrandID,
				this._IP,
				this._Weibo,
				this._Weixin,
				this._Qq,
				this._PhoneNumber,
				this._PhoneInfo,
				this._PhoneHash,
				this._CreateTime,
				this._Type,
				this._Note,
				this._Area,
				this._NoteHash};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ticketcache");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","ticketcache","编号");
			/// <summary>
			/// 关联编号
			/// </summary>
			public readonly static Field BrandID = new Field("BrandID","ticketcache","关联编号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IP = new Field("IP","ticketcache","IP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Weibo = new Field("Weibo","ticketcache","Weibo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Weixin = new Field("Weixin","ticketcache","Weixin");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Qq = new Field("Qq","ticketcache","Qq");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PhoneNumber = new Field("PhoneNumber","ticketcache","PhoneNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PhoneInfo = new Field("PhoneInfo","ticketcache","PhoneInfo");
			/// <summary>
			/// 由phoneInfo getHash
			/// </summary>
			public readonly static Field PhoneHash = new Field("PhoneHash","ticketcache","由phoneInfo getHash");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","ticketcache","CreateTime");
			/// <summary>
			/// TRUE,AUTO,
			/// </summary>
			public readonly static Field Type = new Field("Type","ticketcache","TRUE,AUTO,");
			/// <summary>
			/// 注释
			/// </summary>
			public readonly static Field Note = new Field("Note","ticketcache","注释");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Area = new Field("Area","ticketcache","Area");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NoteHash = new Field("NoteHash","ticketcache","NoteHash");
		}
		#endregion


	}
}

