//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类Users 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("users")]
	[Serializable]
	public partial class Users : Entity 
	{
		#region Model
		private int _Id;
		private bool _IsDelete;
		private string _Name;
		private string _CName;
		private string _Password;
		private int? _RoleID;
		private int? _ParentID;
		private bool _IsLock;
		private DateTime _CreateTime;
		private DateTime? _UpdateTime;
		private string _UpdateReason;
		private bool _IsCompany;
		private string _Tel;
		private string _QQ;
		private string _AuditTel;
		private string _AuditEmail;
		private int? _MaxCategory;
		private string _AuditFile;
		private double _Money;
		private bool _Sex;
		private int? _MemberGroup;
		private int _MemberScore;
		private int _LogTimes;
		private bool _Audit;
		private string _MemberPosition;
		private string _LoginIP;
		/// <summary>
		/// 编号
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsDelete
		{
			get{ return _IsDelete; }
			set
			{
				this.OnPropertyValueChange(_.IsDelete,_IsDelete,value);
				this._IsDelete=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 用户中文名称
		/// </summary>
		public string CName
		{
			get{ return _CName; }
			set
			{
				this.OnPropertyValueChange(_.CName,_CName,value);
				this._CName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Password
		{
			get{ return _Password; }
			set
			{
				this.OnPropertyValueChange(_.Password,_Password,value);
				this._Password=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? RoleID
		{
			get{ return _RoleID; }
			set
			{
				this.OnPropertyValueChange(_.RoleID,_RoleID,value);
				this._RoleID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParentID
		{
			get{ return _ParentID; }
			set
			{
				this.OnPropertyValueChange(_.ParentID,_ParentID,value);
				this._ParentID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsLock
		{
			get{ return _IsLock; }
			set
			{
				this.OnPropertyValueChange(_.IsLock,_IsLock,value);
				this._IsLock=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新原因
		/// </summary>
		public string UpdateReason
		{
			get{ return _UpdateReason; }
			set
			{
				this.OnPropertyValueChange(_.UpdateReason,_UpdateReason,value);
				this._UpdateReason=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsCompany
		{
			get{ return _IsCompany; }
			set
			{
				this.OnPropertyValueChange(_.IsCompany,_IsCompany,value);
				this._IsCompany=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange(_.Tel,_Tel,value);
				this._Tel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AuditTel
		{
			get{ return _AuditTel; }
			set
			{
				this.OnPropertyValueChange(_.AuditTel,_AuditTel,value);
				this._AuditTel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AuditEmail
		{
			get{ return _AuditEmail; }
			set
			{
				this.OnPropertyValueChange(_.AuditEmail,_AuditEmail,value);
				this._AuditEmail=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MaxCategory
		{
			get{ return _MaxCategory; }
			set
			{
				this.OnPropertyValueChange(_.MaxCategory,_MaxCategory,value);
				this._MaxCategory=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AuditFile
		{
			get{ return _AuditFile; }
			set
			{
				this.OnPropertyValueChange(_.AuditFile,_AuditFile,value);
				this._AuditFile=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public double Money
		{
			get{ return _Money; }
			set
			{
				this.OnPropertyValueChange(_.Money,_Money,value);
				this._Money=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MemberGroup
		{
			get{ return _MemberGroup; }
			set
			{
				this.OnPropertyValueChange(_.MemberGroup,_MemberGroup,value);
				this._MemberGroup=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int MemberScore
		{
			get{ return _MemberScore; }
			set
			{
				this.OnPropertyValueChange(_.MemberScore,_MemberScore,value);
				this._MemberScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int LogTimes
		{
			get{ return _LogTimes; }
			set
			{
				this.OnPropertyValueChange(_.LogTimes,_LogTimes,value);
				this._LogTimes=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool Audit
		{
			get{ return _Audit; }
			set
			{
				this.OnPropertyValueChange(_.Audit,_Audit,value);
				this._Audit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MemberPosition
		{
			get{ return _MemberPosition; }
			set
			{
				this.OnPropertyValueChange(_.MemberPosition,_MemberPosition,value);
				this._MemberPosition=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LoginIP
		{
			get{ return _LoginIP; }
			set
			{
				this.OnPropertyValueChange(_.LoginIP,_LoginIP,value);
				this._LoginIP=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.IsDelete,
				_.Name,
				_.CName,
				_.Password,
				_.RoleID,
				_.ParentID,
				_.IsLock,
				_.CreateTime,
				_.UpdateTime,
				_.UpdateReason,
				_.IsCompany,
				_.Tel,
				_.QQ,
				_.AuditTel,
				_.AuditEmail,
				_.MaxCategory,
				_.AuditFile,
				_.Money,
				_.Sex,
				_.MemberGroup,
				_.MemberScore,
				_.LogTimes,
				_.Audit,
				_.MemberPosition,
				_.LoginIP};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._IsDelete,
				this._Name,
				this._CName,
				this._Password,
				this._RoleID,
				this._ParentID,
				this._IsLock,
				this._CreateTime,
				this._UpdateTime,
				this._UpdateReason,
				this._IsCompany,
				this._Tel,
				this._QQ,
				this._AuditTel,
				this._AuditEmail,
				this._MaxCategory,
				this._AuditFile,
				this._Money,
				this._Sex,
				this._MemberGroup,
				this._MemberScore,
				this._LogTimes,
				this._Audit,
				this._MemberPosition,
				this._LoginIP};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","users");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","users","编号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDelete = new Field("IsDelete","users","IsDelete");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","users","名称");
			/// <summary>
			/// 用户中文名称
			/// </summary>
			public readonly static Field CName = new Field("CName","users","用户中文名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Password = new Field("password","users","password");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleID = new Field("RoleID","users","RoleID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentID = new Field("parentID","users","parentID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsLock = new Field("IsLock","users","IsLock");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","users","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","users","UpdateTime");
			/// <summary>
			/// 更新原因
			/// </summary>
			public readonly static Field UpdateReason = new Field("UpdateReason","users","更新原因");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsCompany = new Field("IsCompany","users","IsCompany");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tel = new Field("Tel","users","Tel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QQ = new Field("QQ","users","QQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditTel = new Field("AuditTel","users","AuditTel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditEmail = new Field("AuditEmail","users","AuditEmail");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MaxCategory = new Field("MaxCategory","users","MaxCategory");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditFile = new Field("AuditFile","users","AuditFile");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Money = new Field("Money","users","Money");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","users","Sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MemberGroup = new Field("MemberGroup","users","MemberGroup");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MemberScore = new Field("MemberScore","users","MemberScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LogTimes = new Field("LogTimes","users","LogTimes");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Audit = new Field("Audit","users","Audit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MemberPosition = new Field("MemberPosition","users","MemberPosition");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginIP = new Field("LoginIP","users","LoginIP");
		}
		#endregion


	}
}

